# Generated by Django 4.2.17 on 2025-01-02 06:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('film', '0001_initial'),
        ('user', '0002_alter_user_base'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='base',
        ),
        migrations.AddField(
            model_name='user',
            name='film_history',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='film_history', to='film.film'),
        ),
        migrations.DeleteModel(
            name='Base',
        ),
    ]
